baseURL: https://ferez96.github.io/minhgaugau/
languageCode: en-us
title: Minh Gau Gau

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
